pipeline{
    agent{
        docker {
            image 'python:3.11.9-alpine'
        }
    }
    stages {
        stage('Test') {
            steps {
                sh 'python3 --version'
            }
        }
    }
}