pipeline {
    agent none
    stages {
        stage ('backend') {
            agent{
                docker {
                    image 'python:3.11.9-alpine'
                }
            }
            steps {
                sh 'python3 --verison'
            }
        }
        stage ('frontend') {
            agent {
                docker {
                    image 'node:lts-alpine'
                }
            }
            steps {
                sh 'node --version'
            }
        }
    }
}